--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PRODUCTS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		PRODUCT_NAME VARCHAR(128) NOT NULL,
		PRICE DOUBLE NOT NULL,
		SELLER VARCHAR(40) NOT NULL,
		CONDITION INTEGER NOT NULL,
		IMAGE_PATH VARCHAR(40)
	);

CREATE TABLE USERS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		USERNAME VARCHAR(40) NOT NULL,
		PASSWORD VARCHAR(40) NOT NULL,
		EMAIL VARCHAR(60) NOT NULL,
		FIRST_NAME VARCHAR(30) NOT NULL,
		LAST_NAME VARCHAR(30) NOT NULL,
		GENDER INTEGER NOT NULL
	);

CREATE UNIQUE INDEX SQL181101174616090 ON PRODUCTS (ID ASC);

ALTER TABLE PRODUCTS ADD CONSTRAINT PRIMARY_KEY PRIMARY KEY (ID);